export const masterProfile = Object.freeze({
  person: {
    name: "Maxence Roques",
    phone: "+33667702014",
    phoneLabel: "+33 6 67 70 20 14",
    email: "maxenceroques67@gmail.com",
    linkedin: "https://www.linkedin.com/in/maxence-roques/",
    github: "https://github.com/MaxenceRoques",
    portfolio: "https://maxenceroques.github.io/portfolio/",
    photo: "assets/portrait-maxence.jpg",
  },
  education: [
    "2023 – 2026 · Cycle ingénieur informatique, spécialité Interaction Homme-Machine — Polytech Nice Sophia",
    "2025 · TOEIC : 970/990 — Polytech Nice Sophia",
    "2021 – 2023 · CPGE PSI — Lycée Couffignal",
  ],
  languages: ["Français : natif", "Anglais : courant", "Allemand : intermédiaire"],
  educationEn: [
    "2023 – 2026 · Engineering degree in Computer Science, Human-Computer Interaction specialization — Polytech Nice Sophia",
    "2025 · TOEIC: 970/990 — Polytech Nice Sophia",
    "2021 – 2023 · PSI preparatory class — Lycée Couffignal",
  ],
  languagesEn: ["French: native", "English: fluent", "German: intermediate"],
  additionalEn: ["Driving licence (B)", "Student representative for the Information Systems and HCI track (2024 – 2026)"],
  additional: ["Permis B", "Responsable de la filière SI et IHM (2024 – 2026)"],
  skills: {
    frontend: ["React", "TypeScript", "JavaScript", "Angular", "HTML5 / CSS"],
    frontendEn: ["React", "TypeScript", "JavaScript", "Angular", "HTML5 / CSS"],
    fullstackPrimary: ["React", "TypeScript", "JavaScript", "Node.js", "Next.js", "Zod"],
    javaPrimary: ["Java 17/21", "Spring Boot", "Spring Data JPA", "API REST", "Maven"],
    angularPrimary: ["Angular", "TypeScript"],
    javaWorkflow: ["PostgreSQL", "Docker", "Docker Compose", "JUnit", "Mockito", "Cucumber", "CI/CD", "Jenkins", "GitHub Actions"],
    javaComplementary: ["React", "Node.js", "IA appliquée"],
    backend: ["Node.js", "Java 17/21", "Spring Boot", "Spring Data JPA", "API REST", "Python", "PHP"],
    ai: ["Mistral AI", "n8n", "évaluation LLM", "LLM-as-a-Judge", "jeux de tests", "Mistral Batch", "Random Forest"],
    aiEn: ["Mistral AI", "n8n", "LLM evaluation", "test datasets", "Mistral Batch", "Random Forest"],
    systems: ["WebSocket", "Kafka", "Redis", "PostgreSQL", "Docker", "InfluxDB", "SQLite"],
    backendSystemsEn: ["Node.js", "Python", "REST APIs", "WebSocket", "Kafka", "Redis", "Docker"],
    quality: ["JUnit", "Mockito", "Cucumber", "GitHub Actions", "Jenkins", "Playwright"],
    product: ["Conception centrée utilisateur", "Accessibilité", "Entretiens utilisateurs", "Documentation"],
    productEn: ["User-centred design", "Accessibility", "User interviews", "Documentation"],
  },
  entries: {
    nextsourcia: {
      title: "Développeur full-stack IA — Nextsourcia", date: "Mars – juillet 2026 · 5 mois",
      context: "Stage de fin d’études · Plateforme SaaS RH réunissant gestion opérationnelle, pilotage et assistance par IA.",
      bullets: {
        product: ["Conçu des interfaces de pilotage permettant aux équipes de visualiser des données métier en temps réel, alimentées par WebSocket, Kafka et Redis.", "Structuré le cycle de vie de près de 50 configurations IA — versionnement, publication, déploiement, rollback et synchronisation — afin de faire évoluer prompts et modèles de manière traçable.", "Mis en place une chaîne d’évaluation pré-production orchestrée par n8n, combinant jeux de tests, traitements Mistral Batch, benchmarks et juges LLM automatisés pour comparer les configurations avant déploiement.", "Analysé les cas d’erreur et les retours disponibles afin d’identifier les axes d’évolution des chaînes d’enrichissement documentaire et de scoring."],
        saas: ["Conçu des interfaces de pilotage temps réel alimentées par WebSocket, Kafka et Redis.", "Structuré le cycle de vie de près de 50 configurations IA — versionnement, publication, déploiement, rollback et synchronisation — pour une évolution traçable des prompts et modèles.", "Mis en place une chaîne d’évaluation pré-production orchestrée par n8n avec jeux de tests, Mistral Batch, benchmarks et juges LLM."],
        en: ["Built real-time operational dashboards backed by WebSocket, Kafka and Redis.", "Structured the lifecycle of nearly 50 AI configurations: versioning, publishing, deployment, rollback and synchronization.", "Set up a pre-production evaluation workflow with n8n, test datasets, Mistral Batch, benchmarks and automated LLM judges."],
      },
      en: { title: "Full-Stack AI Developer — Nextsourcia", date: "March – July 2026 · 5 months", context: "Final-year internship · HR SaaS platform combining operations, business monitoring and AI assistance.", techLabel: "Technologies" },
      tech: "React, Node.js, Mistral AI, n8n, WebSocket, Kafka, Redis, Zod",
    },
    gtb: {
      title: "Projet d’ingénierie — Polytech Nice Sophia / Université Côte d’Azur", date: "Oct. 2025 – fév. 2026 · 5 mois",
      context: "Projet d’équipe pour GECOS : supervision et routage multicanal des alertes GTB.",
      bullets: { default: ["Recueilli les besoins des équipes techniques afin de définir un routage d’alertes compatible avec leurs outils opérationnels.", "Développé un service Docker extensible par plugins pour centraliser, synthétiser et persister les alertes provenant d’InfluxDB.", "Intégré un routage résilient vers Kanboard, Slack, Teams et SMS, avec mécanisme de reprise sur erreur.", "Développé six plugins PHP pour adapter Kanboard aux processus métier et aux retours des utilisateurs."], en: ["Gathered requirements from technical teams to define alert routing compatible with operational tools.", "Built a Docker service extensible through plugins to centralize, summarize and persist InfluxDB alerts.", "Integrated resilient routing to Kanboard, Slack, Teams and SMS with error recovery."] },
      en: { title: "Engineering project — Polytech Nice Sophia / Université Côte d’Azur", date: "Oct. 2025 – Feb. 2026 · 5 months", context: "Team project for GECOS: building-management alert supervision and multichannel routing.", techLabel: "Technologies" }, tech: "InfluxDB, Flux, SQLite, Telegraf, PHP, Kanboard, Docker, API",
    },
    dniit: {
      title: "Stage développement IA — DNIIT", date: "Mai – août 2025 · 4 mois",
      context: "Stage au Vietnam, mené en autonomie sur un système prédictif d’alerte incendie.",
      bullets: { default: ["Préparé les données et entraîné des modèles Random Forest pour estimer le risque de départ de feu.", "Développé un tableau de bord React rendant les niveaux de risque lisibles et exploitables."], en: ["Prepared data and trained Random Forest models to estimate wildfire risk.", "Built a React dashboard making risk levels readable and actionable."] }, en: { title: "AI Development Internship — DNIIT", date: "May – Aug. 2025 · 4 months", context: "Internship in Vietnam, independently delivering a wildfire-risk prediction system.", techLabel: "Technologies" }, tech: "Python, React, Random Forest",
    },
    juno: { title: "Projet personnel — Juno", date: "2026", context: "Application full-stack de suivi de recherche d’emploi, conçue et utilisée sur des cas réels.", bullets: { default: ["Conçu le produit, le modèle de données et les parcours utilisateurs.", "Développé l’application de bout en bout avec React / Next.js / TypeScript, logique serveur et base relationnelle.", "Ajouté des fonctions d’assistance IA pour l’import d’offres, l’adaptation de CV et la préparation de brouillons.", "Mis en place des tests automatisés et un audit UX desktop/mobile."], saas: ["Conçu les parcours, le modèle de données et les fonctions d’import d’offres, d’adaptation de CV et de préparation de brouillons assistées par IA.", "Développé l’application avec Next.js, TypeScript, logique serveur, SQLite / Cloudflare D1, tests automatisés et audit UX."], en: ["Designed the product, data model and user journeys for a job-search tracking application.", "Developed it end-to-end with React, Next.js, TypeScript, server logic and a relational database.", "Added AI-assisted job import, CV tailoring and draft-preparation features, plus automated tests and a desktop/mobile UX audit."] }, en: { title: "Personal project — Juno", date: "2026", context: "Full-stack job-search tracking application, designed and used on real cases.", techLabel: "Technologies" }, tech: "React, Next.js, TypeScript, Cloudflare D1 / SQLite, Drizzle ORM, Playwright" },
    loyalty: { title: "Projet académique — Carte multi-fidélité", date: "Jan. – avr. 2025 · 4 mois", context: "Système distribué de carte de fidélité : partenaires, avantages, transactions et statistiques.", bullets: { default: ["Développé des API REST en Java 21 et Spring Boot pour gérer cartes, partenaires, avantages, historiques et statistiques.", "Modélisé les entités métier et leur persistance dans PostgreSQL avec Spring Data JPA.", "Automatisé les tests JUnit/Cucumber et la construction des images via une chaîne CI/CD Jenkins."] }, tech: "Java 21, Spring Boot, Spring Data JPA, PostgreSQL, JUnit, Cucumber, Docker, Jenkins" },
    eats: { title: "Projet académique — SophiaTech Eats", date: "Sept. – déc. 2024 · 4 mois", context: "Application de restauration : recherche, commande et offres selon le profil client.", bullets: { default: ["Contribué à une interface Angular 18 structurée en composants, services et modèles pour les parcours d’authentification, recherche et commande.", "Développé un backend Java 17 en services d’authentification, commande et paiement derrière une passerelle HTTP.", "Assuré la QA avec scénarios BDD Cucumber et tests JUnit/Mockito intégrés à GitHub Actions."] }, tech: "Angular 18, TypeScript, Java 17, API REST, JWT, Cucumber, JUnit, Mockito, GitHub Actions" },
    tron: { title: "Projet académique — Jeu de Tron", date: "Jan. – avr. 2025 · 3 mois", context: "Jeu de Tron multijoueur en équipe déployé sur AWS.", bullets: { default: ["Développé le système d’amis et les mécaniques de gamification.", "Réalisé les modes de jeu local et en ligne, avec adversaire contrôlé par une IA.", "Déployé l’application multijoueur sur AWS."], en: ["Built the friends system and gamification mechanics.", "Implemented local and online game modes, including an AI-controlled opponent.", "Deployed the multiplayer application on AWS."] }, en: { title: "Academic project — Tron game", date: "Jan. – Apr. 2025 · 3 months", context: "Team multiplayer Tron game deployed on AWS.", techLabel: "Technologies" }, tech: "HTML, CSS, JavaScript, AWS" },
  },
});
